"""
Django settings for petty project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

import mimetypes
import os
import dj_database_url

mimetypes.add_type("text/css", ".css", True)

from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'PettyApp'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'petty.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'petty.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 8 
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=20), 
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

JAZZMIN_SETTINGS = {

    # 🔥 BRANDING
    "site_title": "Waggy Admin",
    "site_header": "Waggy Control Panel",
    "site_brand": "Waggy",
    "welcome_sign": "Welcome to Waggy Admin 🚀",

    # 🔥 LOGO (make sure this exists → static/images/logo.png)
    "site_logo": "images/logo.png",
    "login_logo": "images/logo.png",

    "copyright": "Petty © 2026",

    # 🔥 SIDEBAR ORDER
    "order_with_respect_to": [
        "PettyApp.Product",
        "auth.user",
        "PettyApp.Order",
        "PettyApp.OrderItem",
        "PettyApp.Category",
        "PettyApp.Profile",
        "PettyApp.Address",
        "PettyApp.Review",
        "PettyApp.Blog",
        "PettyApp.Comment",
        "PettyApp.Reply",
        "PettyApp.Testimonial",
        "PettyApp.Subscriber",
        "PettyApp.Cart",
        "PettyApp.CartItem",
        "PettyApp.Wishlist",
    ],

    # 🔥 ICONS
    "icons": {
    "auth.user": "fas fa-user",
    "auth.Group": "fas fa-users",

    "PettyApp.Product": "fas fa-box",
    "PettyApp.Order": "fas fa-shopping-cart",
    "PettyApp.OrderItem": "fas fa-list",
    "PettyApp.Category": "fas fa-tags",

    "PettyApp.Blog": "fas fa-blog",
    "PettyApp.Comment": "fas fa-comments",
    "PettyApp.Reply": "fas fa-reply",

    "PettyApp.Profile": "fas fa-id-card",
    "PettyApp.Address": "fas fa-map-marker-alt",

    "PettyApp.Cart": "fas fa-cart-plus",
    "PettyApp.CartItem": "fas fa-shopping-basket",

    "PettyApp.Wishlist": "fas fa-heart",
    "PettyApp.Testimonial": "fas fa-star",
    "PettyApp.Subscriber": "fas fa-envelope",
    },

    "hide_models": [
    "PettyApp.CartItem",
    "PettyApp.OrderItem",
    "PettyApp.BlogLike",
    "PettyApp.Reply",
],

    # 🔥 UI BEHAVIOR
    "show_sidebar": True,
    "navigation_expanded": True,

    # 🔥 TOP NAV
    "topmenu_links": [
        {"name": "Home", "url": "/", "permissions": ["auth.view_user"]},
    ],

    # 🔥 OPTIONAL (safe theme)
    "theme": "default",
}

GEMINI_API = os.getenv("GEMINI_API")

RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET")


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.parse(os.getenv("DATABASE_URL"))
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = "Waggy <waggypetshop66@gmail.com>"

FRONTEND_URL = os.getenv("FRONTEND_URL")


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CORS_ALLOW_ALL_ORIGINS = True