# Generated by Django 6.0.3 on 2026-03-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PettyApp', '0003_product_is_approved_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='password',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
