# Generated by Django 6.0.3 on 2026-03-26 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PettyApp', '0005_testimonial_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='name',
        ),
    ]
