# Generated by Django 6.0.3 on 2026-03-30 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PettyApp', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_best_selling',
        ),
    ]
