# Generated by Django 6.0.3 on 2026-03-30 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PettyApp', '0008_remove_product_is_best_selling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='PettyApp.product'),
        ),
    ]
