# Generated by Django 6.0.3 on 2026-03-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PettyApp', '0010_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
