# Generated by Django 6.0.3 on 2026-03-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PettyApp', '0014_order_address_order_status_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
