# Generated by Django 6.0.3 on 2026-04-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PettyApp', '0016_order_is_paid_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('ONLINE', 'Online Payment')], default='COD', max_length=20),
        ),
    ]
