# Generated by Django 6.0.3 on 2026-04-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PettyApp', '0019_alter_cartitem_cart_alter_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('None', 'None'), ('Processed', 'Processed')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='return_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='return_status',
            field=models.CharField(choices=[('None', 'None'), ('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='None', max_length=20),
        ),
    ]
